Update ataglance

diff --git a/ataglance b/ataglance
--- a/ataglance
+++ b/ataglance
@@ -26,6 +26,7 @@ while true; do
         echo "No Panel"
       ;;
       "*")
-        echo "Invalid Input"; break;
+        echo "Invalid Input";
+        exit 1;
   esac
 done;
